apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weatherapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Anand-1912/argocd-app-config-main.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: weatherapp
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
