apiVersion: v1
kind: Service
metadata:
  name: weatherapp-service
  labels:
    app: weatherapp
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30099
  selector:
    app: weatherapp
