apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp
  labels:
    app: weatherapp
spec:
  selector:
    matchLabels:
      app: weatherapp
  replicas: 4
  template:
    metadata:
      labels:
        app: weatherapp
    spec:
      containers:
        - name: weatherapp
          image: anand1912/weatherapp:v2
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
